//
// APP.C
// Isolate my code here, separate from the autogenerated CubeMX stuff
//


#include <stdio.h>
#include <string.h>

#include "main.h"

#include "app.h"
#include "adc_dac.h"
#include "ring_buffer.h"
#include "dbgmon.h"





// printf rediect to CDC stuff
#include "usbd_cdc_if.h"

int _write(int file, char *ptr, int len)
{
    // Send data over USB CDC FS
    // A timeout loop ensures the previous transmission finished before sending new data
    uint32_t start_time = HAL_GetTick();
    while (CDC_Transmit_FS((uint8_t*)ptr, len) == USBD_BUSY) {
        if ((HAL_GetTick() - start_time) > 100) { // 100ms timeout safety
            return -1; 
        }
    }
    return len;
}


// scanf rediect to CDC stuff
volatile char usb_rx_char = 0;
volatile uint8_t usb_rx_ready = 0;

void CDC_Receive_FS_hook(uint8_t* Buf, uint32_t Len)
{
  if (Len > 0) {
      usb_rx_char = Buf[0]; // Capture the first incoming character
      usb_rx_ready = 1;     // Flag to notify _read
  }
}


bool is_usb_read_ready(void)
{
   return usb_rx_ready != 0;
}

int _read(int file, char *ptr, int len)
{
    int index = 0;
    while (index < len) {
        while (!usb_rx_ready)   // Wait until a character arrives via USB interrupt
           ; 
        
        ptr[index] = usb_rx_char;
        usb_rx_ready = 0; // Clear the flag        
        index++;
    }
    return index;
}

//End of printf/scanf redirection





//Called at top of main(), before HAL_Init()
void app_init1(void)
{
   setvbuf(stdin, NULL, _IONBF, 0);  // Turn off line buffering for scanf
   setvbuf(stdout, NULL, _IONBF, 0); // Disables buffering on stdout, for printf debugging 
}



//Called from main, after the generated peripheral initialization sequence
void app_init2(void)
{
   // There needs to be a delay for USB to enumerated and connect before the first printf.
   // I have not found a robust way to check of if the connection is up yet, so this is a bit of a hack
   HAL_Delay(2000);
   
   
#if 0   
   HAL_TIM_PWM_Start(&htim5, TIM_CHANNEL_4);   //Start PWM sqaure wave generation on PA3 (CN9, p1)
   

   // Using TIM2 running at ~48Khz to trigger ADC1 and DAC1 conversions
   // ADC1 is set for 8x oversampling 
   HAL_TIM_Base_Start(&htim2);  // Turn on TIM2. It will instantly start emitting 48,012Hz update pulses

#endif

   dbm_init();                  // Start the serial debug monitor
}


//Called at the bottom of the while loop in main()
void app_loop_bottom(void)
{
   dbm_processChar();           // Debug monitor process

//    HAL_GPIO_WritePin(LD6_GPIO_Port, LD6_Pin, GPIO_PIN_SET);
//    HAL_Delay(100);
//    HAL_GPIO_WritePin(LD6_GPIO_Port, LD6_Pin, GPIO_PIN_RESET);
//    HAL_Delay(1000);
}








/////////////////////////////////////////////////////////////////
// Old code, from main loop
/////////////////////////////////////////////////////////////////


#if 0   //Not longer would work with DMA setup, this is for polling
    {
       // Write a value to the DAC (Example for 12-bit resolution: 0 to 4095)
       HAL_DAC_SetValue(&hdac1, DAC_CHANNEL_1, DAC_ALIGN_12B_L, sample);
    }
#endif
